const delegations = {
  Ariana: [
    'Ariana Ville',
    'Raoued',
    'La Soukra',
    'Sidi Thabet',
    'Ettadhamen',
    'Kalaat el Andalous'
  ],
  Béja: [
    'Béja Nord',
    'Béja Sud',
    'Testour',
    'Nefza',
    'Téboursouk',
    'Medjez el-Bab',
    'Amdoun',
    'Goubellat',
    'Thibar'
  ],
  'Ben Arous': [
    'Ben Arous Ville',
    'Mornag',
    'Mourouj',
    'Rades',
    'Ezzahra',
    'Hammam Lif',
    'Hammam Chatt',
    'Bou Mhel el-Bassatine',
    'Fouchana',
    'Mohamedia',
    'El Mourouj'
  ],
  Bizerte: [
    'Bizerte Nord',
    'Bizerte Sud',
    'Mateur',
    'Sejnane',
    'Ras Jebel',
    'El Alia',
    'Ghar El Melh',
    'Menzel Bourguiba',
    'Menzel Jemil',
    'Tinja',
    'Utique'
  ],
  Gabès: [
    'Gabès Ville',
    'Gabès Sud',
    'Gabès Ouest',
    'Matmata',
    'Matmata Nouvelle',
    'Ghannouch',
    'El Hamma',
    'Mareth',
    'Nouvelle Matmata',
    'Métouia'
  ],
  Gafsa: [
    'Gafsa Nord',
    'Gafsa Sud',
    'Redeyef',
    'Metlaoui',
    'Oum Larayes',
    'El Ksar',
    'Moularès',
    'Sened',
    'Sidi Aïch'
  ],
  Jendouba: [
    'Jendouba Nord',
    'Jendouba Sud',
    'Ghardimaou',
    'Fernana',
    'Tabarka',
    'Balta Bou Aouane',
    'Aïn Draham',
    'Bou Salem',
    'Oued Meliz'
  ],
  Kairouan: [
    'Kairouan Nord',
    'Kairouan Sud',
    'Chebika',
    'Sbikha',
    'Oueslatia',
    'Hajeb El Ayoun',
    'Nasrallah',
    'Bouhajla',
    'Chrarda',
    'Echrarda'
  ],
  Kasserine: [
    'Kasserine Nord',
    'Kasserine Sud',
    'Sbeitla',
    'Sbeïtla',
    'Feriana',
    'Thala',
    'Foussana',
    'Hassi El Ferid',
    'Hidra',
    'Jedelienne',
    'Ezzouhour'
  ],
  Kebili: [
    'Kebili Nord',
    'Kebili Sud',
    'Douz Nord',
    'Douz Sud',
    'Souk Lahad',
    'El Faouar'
  ],
  Kef: [
    'Kef Est',
    'Kef Ouest',
    'Dahmani',
    'Touiref',
    'Sakiet Sidi Youssef',
    'Nebeur',
    'Tajerouine',
    'Kalaat Khasba',
    'Kalaat Senan',
    'Jerissa',
    'El Ksour',
    'Tejerouine'
  ],
  Mahdia: [
    'Mahdia Ville',
    'Chebba',
    'Ksour Essef',
    'El Jem',
    'Bou Merdes',
    'Souassi',
    'Hiboun',
    'Ouled Chamekh',
    'Chorbane',
    'Sidi Alouane',
    'Melloulech'
  ],
  Manouba: [
    'Manouba Ville',
    'Douar Hicher',
    'Oued Ellil',
    'Den Den',
    'Mornaguia',
    'Borj El Amri',
    'El Battan',
    'Tebourba',
    'Jedaida'
  ],
  Médenine: [
    'Médenine Nord',
    'Médenine Sud',
    'Ben Gardane',
    'Zarzis',
    'Beni Khedache',
    'Sidi Makhlouf',
    'Jerba Houmt Souk',
    'Jerba Midoun',
    'Jerba Ajim'
  ],
  Monastir: [
    'Monastir Ville',
    'Ksar Hellal',
    'Jemmal',
    'Zeramdine',
    'Bekalta',
    'Bembla',
    'Sahline',
    'Ksibet El Mediouni',
    'Sayada',
    'Moknine',
    'Teboulba',
    'Amira'
  ],
  Nabeul: [
    'Nabeul Ville',
    'Hammamet',
    'Korba',
    'Grombalia',
    'Menzel Temime',
    'Menzel Bouzelfa',
    'Dar Chaabane El Fehri',
    'Kelibia',
    'Soliman',
    'Takelsa',
    'Béni Khiar',
    'El Haouaria'
  ],
  Sfax: [
    'Sfax Ville',
    'Sfax Sud',
    'Sfax Ouest',
    'Sakiet Eddaier',
    'Sakiet Ezzit',
    'Agareb',
    'Jebeniana',
    'El Hencha',
    'Mahrès',
    'Kerkennah',
    'Bir Ali Ben Khalifa'
  ],
  'Sidi Bouzid': [
    'Sidi Bouzid Est',
    'Sidi Bouzid Ouest',
    'Meknassy',
    'Menzel Bouzaiane',
    'Regueb',
    'Ouled Haffouz',
    'Jilma',
    'Mezzouna',
    'Souk Jedid',
    'Cebbala Ouled Asker',
    'Sidi Ali Ben Aoun'
  ],
  Siliana: [
    'Siliana Nord',
    'Siliana Sud',
    'Gaâfour',
    'Kesra',
    'Bargou',
    'El Krib',
    'Bou Arada',
    'Makthar',
    'Rouhia',
    'El Aroussa'
  ],
  Sousse: [
    'Sousse Ville',
    'Sousse Nord',
    'Sousse Sud',
    'Akouda',
    'Hammam Sousse',
    'Msaken',
    'Kalaa Sghira',
    'Kalaa Kebira',
    'Enfidha',
    'Kondar',
    'Sidi Bou Ali',
    'Sidi El Heni',
    'Hergla'
  ],
  Tataouine: [
    'Tataouine Nord',
    'Tataouine Sud',
    'Bir Lahmar',
    'Dhiba',
    'Ghomrassen',
    'Remada',
    'Smâr'
  ],
  Tozeur: [
    'Tozeur Ville',
    'Degache',
    'Nefta',
    'Tamaghza',
    'Hazoua'
  ],
  Tunis: [
    'Tunis Ville',
    'Bab El Bhar',
    'Bab Souika',
    'Carthage',
    'El Kabaria',
    'El Menzah',
    'El Omrane',
    'El Omrane Supérieur',
    'El Ouardia',
    'Ettahrir',
    'Djebel Jelloud',
    'La Goulette',
    'La Marsa',
    'Le Bardo',
    'Sidi El Béchir',
    'Sidi Hassine'
  ],
  
  Zaghouan: [
    'Zaghouan Ville',
    'Bir Mcherga',
    'El Fahs',
    'Nadhour',
    'Saouaf',
    'Zriba'
  ]
  
};

export default delegations;